cask_args appdir: '/Applications'

tap 'homebrew/bundle'
#tap 'puma/puma'

brew 'coreutils'
brew 'imagemagick'
brew 'openssl'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

#cask '1password'
#cask 'firefox'
#cask 'google-chrome'
#cask 'slack'
#cask 'steam'
#cask 'tunnelbear'
#cask 'vlc'
